In [1]:
import pandas as pandas
import matplotlib.pyplot as plot
import numpy as numpy
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import re
import string
import cv2
import tensorflow as tf
from keras.utils import to_categorical
from sklearn.utils import shuffle
from tensorflow import keras
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
from keras.layers import Flatten
from tensorflow.keras import layers
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Dense
from keras.layers import Bidirectional
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import array_to_img
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Embedding, Dense, Dropout, GlobalMaxPooling1D, MaxPool2D, SimpleRNN, Flatten, BatchNormalization, Conv2D
from sklearn.metrics import classification_report, confusion_matrix
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [32]:
#Завдання 1
suicide = pandas.read_csv("/home/anatoliy/Downloads/master.csv")
print(suicide.columns)
print("Raws,Columns:")
print(suicide.shape)
suicide = suicide.dropna() 
suicide.isnull().sum()

Index(['country', 'year', 'sex', 'age', 'suicides_no', 'population',
       'suicides/100k pop', 'country-year', 'HDI for year',
       ' gdp_for_year ($) ', 'gdp_per_capita ($)', 'generation'],
      dtype='object')
Raws,Columns:
(31756, 12)


country               0
year                  0
sex                   0
age                   0
suicides_no           0
population            0
suicides/100k pop     0
country-year          0
HDI for year          0
 gdp_for_year ($)     0
gdp_per_capita ($)    0
generation            0
dtype: int64

In [33]:
suicide_only_numbers  = suicide.drop(columns=['sex', 'age', 'suicides_no', 'country-year','population', 'generation', ' gdp_for_year ($) ', 'gdp_per_capita ($)'], axis=1).set_index('country') #Getting numbers
X = suicide_only_numbers.drop(['year'], axis=1)
Y = suicide_only_numbers['year']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30)
print(X_train.shape)
print(Y_train.shape)

(7770, 2)
(7770,)


In [34]:
model = Sequential()
model.add(layers.Dense(32, activation="relu"))
model.add(layers.Dense(32, activation="relu"))
model.add(Dense(1, activation='sigmoid'))
model.add(layers.Flatten())
model.build(input_shape=(None, 2)) 
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 32)                96        
                                                                 
 dense_13 (Dense)            (None, 32)                1056      
                                                                 
 dense_14 (Dense)            (None, 1)                 33        
                                                                 
 flatten_4 (Flatten)         (None, 1)                 0         
                                                                 
Total params: 1,185
Trainable params: 1,185
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, Y_train, epochs=100, validation_split=0.2)

Epoch 1/100
195/195 [==============================] - 2s 5ms/step - loss: -17764.4492 - accuracy: 0.0000e+00 - val_loss: -30090.3965 - val_accuracy: 0.0000e+00
Epoch 2/100
195/195 [==============================] - 1s 4ms/step - loss: -30588.5938 - accuracy: 0.0000e+00 - val_loss: -30607.8789 - val_accuracy: 0.0000e+00
Epoch 3/100
195/195 [==============================] - 1s 5ms/step - loss: -30613.1836 - accuracy: 0.0000e+00 - val_loss: -30608.2031 - val_accuracy: 0.0000e+00
Epoch 4/100
195/195 [==============================] - 1s 4ms/step - loss: -30613.2383 - accuracy: 0.0000e+00 - val_loss: -30608.4043 - val_accuracy: 0.0000e+00
Epoch 5/100
195/195 [==============================] - 1s 4ms/step - loss: -30613.3047 - accuracy: 0.0000e+00 - val_loss: -30608.5176 - val_accuracy: 0.0000e+00
Epoch 6/100
195/195 [==============================] - 1s 4ms/step - loss: -30613.3047 - accuracy: 0.0000e+00 - val_loss: -30608.6406 - val_accuracy: 0.0000e+00
Epoch 7/100
195/195 [=============

In [36]:
Y_prediction = model.predict(X_test) > 0.5
print(confusion_matrix(Y_test, Y_prediction))
print(classification_report(Y_test, Y_prediction))
#Результат майже такий самий

105/105 [==============================] - 0s 2ms/step
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [143   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [175   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [227   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [266   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [279   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [298   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [283   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [291   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [278   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [248   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [286   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [251   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [225   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 80   0   0   0   0   0   0   0   0   0   0   0   0   0   0]]