In [1]:
import codecs
from transformers import pipeline
from ipywidgets import FloatProgress
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

In [2]:
classifier = pipeline('sentiment-analysis')

All model checkpoint weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [4]:
text_one = 'Romacnhencko'
classifier(text_one)

[{'label': 'NEGATIVE', 'score': 0.7581807971000671}]

In [5]:
text_two = 'Anatolyi'
classifier(text_two)

[{'label': 'POSITIVE', 'score': 0.9744058847427368}]

In [6]:
text_three = 'FB-21mp'
classifier(text_three)

[{'label': 'NEGATIVE', 'score': 0.9895161390304565}]

In [7]:
text_four = 'IPT'
classifier(text_four)

[{'label': 'NEGATIVE', 'score': 0.5971274375915527}]

In [8]:
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFAutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Some weights of the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_39']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [9]:
inputs = tokenizer([text_one, text_two])
inputs

{'input_ids': [[101, 12836, 2278, 25311, 2368, 19665, 102], [101, 9617, 3406, 2135, 2072, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]}

In [10]:
inputs_with_padding = tokenizer([text_one, text_two], padding = True, truncation = True, max_length = 256, return_tensors="tf")
inputs_with_padding

{'input_ids': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[  101, 12836,  2278, 25311,  2368, 19665,   102],
       [  101,  9617,  3406,  2135,  2072,   102,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0]], dtype=int32)>}

In [11]:
outputs = model(inputs_with_padding)
outputs

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.69444466, -0.44829053],
        [-1.778941  ,  1.8605208 ]], dtype=float32)>,)

In [12]:
predictions = tf.nn.softmax(outputs[0], axis=-1)
predictions

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.7581815 , 0.24181853],
       [0.0255942 , 0.9744058 ]], dtype=float32)>

In [13]:
inputs = tokenizer([text_one, text_two, text_three])
inputs

{'input_ids': [[101, 12836, 2278, 25311, 2368, 19665, 102], [101, 9617, 3406, 2135, 2072, 102], [101, 1042, 2497, 1011, 2538, 8737, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]]}

In [14]:
inputs_with_padding = tokenizer([text_one, text_two, text_three], padding = True, truncation = True, max_length = 256, return_tensors="tf")
inputs_with_padding

{'input_ids': <tf.Tensor: shape=(3, 7), dtype=int32, numpy=
array([[  101, 12836,  2278, 25311,  2368, 19665,   102],
       [  101,  9617,  3406,  2135,  2072,   102,     0],
       [  101,  1042,  2497,  1011,  2538,  8737,   102]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(3, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [15]:
outputs = model(inputs_with_padding)
outputs

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.6944459, -0.4482916],
        [-1.7789414,  1.8605213],
        [ 2.4833722, -2.0640042]], dtype=float32)>,)

In [16]:
predictions = tf.nn.softmax(outputs[0], axis=-1)
predictions

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7581819 , 0.24181813],
       [0.02559419, 0.9744058 ],
       [0.98951614, 0.01048389]], dtype=float32)>

In [17]:
inputs = tokenizer([text_one, text_two, text_three, text_four])
inputs

{'input_ids': [[101, 12836, 2278, 25311, 2368, 19665, 102], [101, 9617, 3406, 2135, 2072, 102], [101, 1042, 2497, 1011, 2538, 8737, 102], [101, 12997, 2102, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1]]}

In [18]:
inputs_with_padding = tokenizer([text_one, text_two, text_three, text_four], padding = True, truncation = True, max_length = 256, return_tensors="tf")
inputs_with_padding

{'input_ids': <tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[  101, 12836,  2278, 25311,  2368, 19665,   102],
       [  101,  9617,  3406,  2135,  2072,   102,     0],
       [  101,  1042,  2497,  1011,  2538,  8737,   102],
       [  101, 12997,  2102,   102,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 0, 0]], dtype=int32)>}

In [19]:
outputs = model(inputs_with_padding)
outputs

(<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[ 0.69444466, -0.4482905 ],
        [-1.7789401 ,  1.8605196 ],
        [ 2.4833715 , -2.0640037 ],
        [ 0.3297063 , -0.06381004]], dtype=float32)>,)

In [20]:
nlp_qusetion_answering = pipeline('question-answering')
nlp_qusetion_answering(context='Yes', question='Will Ukraine win?')

Some weights of the model checkpoint at distilbert-base-cased-distilled-squad were not used when initializing TFDistilBertForQuestionAnswering: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing TFDistilBertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of TFDistilBertForQuestionAnswering were not initialized from the model checkpoint at distilbert-base-cased-distilled-squad and are newly initialized: ['dropout_59']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/kali/anaconda3/envs/teststackoverflow/lib/pyth

{'answer': 'Yes', 'end': 2, 'score': 0.5990897417068481, 'start': 0}